/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood_bank_management_system;

/**
 *
 * @author canVarli
 */
public class UpdateRecipientDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateRecipientDetailsFrame
     */
    public UpdateRecipientDetailsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBox_recipient_blood_group = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfield_recipient_contact_number = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_recipient_remarks = new javax.swing.JTextArea();
        textfield_recipient_search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textfield_recipient_complete_address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textfield_recipient_fullName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBox_recipient_blood_group.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBox_recipient_blood_group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "0+", "0-" }));
        comboBox_recipient_blood_group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_recipient_blood_groupActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox_recipient_blood_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 139, 255, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE RECİPİENT DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 410, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Recipient ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 59, -1, -1));

        textfield_recipient_contact_number.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textfield_recipient_contact_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_recipient_contact_numberActionPerformed(evt);
            }
        });
        jPanel1.add(textfield_recipient_contact_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 255, -1));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 56, -1, -1));

        textArea_recipient_remarks.setColumns(20);
        textArea_recipient_remarks.setRows(5);
        jScrollPane1.setViewportView(textArea_recipient_remarks);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 255, -1));

        textfield_recipient_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textfield_recipient_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_recipient_searchActionPerformed(evt);
            }
        });
        jPanel1.add(textfield_recipient_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 56, 82, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, -1, -1));

        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_bank_management_system/save.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Recipient Blood Group");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, -1, -1));

        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_bank_management_system/Exit application.png"))); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Complete Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 107, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Contact Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        textfield_recipient_complete_address.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textfield_recipient_complete_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_recipient_complete_addressActionPerformed(evt);
            }
        });
        jPanel1.add(textfield_recipient_complete_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 255, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Remarks");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        textfield_recipient_fullName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textfield_recipient_fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_recipient_fullNameActionPerformed(evt);
            }
        });
        jPanel1.add(textfield_recipient_fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 96, 255, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood_bank_management_system/all page background image.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_recipient_contact_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_recipient_contact_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_recipient_contact_numberActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    private void textfield_recipient_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_recipient_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_recipient_searchActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainPageFrame mainPageFrame = new MainPageFrame();
        mainPageFrame.setVisible(true);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void textfield_recipient_fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_recipient_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_recipient_fullNameActionPerformed

    private void comboBox_recipient_blood_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_recipient_blood_groupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_recipient_blood_groupActionPerformed

    private void textfield_recipient_complete_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_recipient_complete_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_recipient_complete_addressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRecipientDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRecipientDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> comboBox_recipient_blood_group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea_recipient_remarks;
    private javax.swing.JTextField textfield_recipient_complete_address;
    private javax.swing.JTextField textfield_recipient_contact_number;
    private javax.swing.JTextField textfield_recipient_fullName;
    private javax.swing.JTextField textfield_recipient_search;
    // End of variables declaration//GEN-END:variables
}
